### ISSUE TITLE
Typo in TheaterExamples.java

### ISSUE THREAD

**Issue by niemasd** [IPCPS/playground-9dxcuq8k#1]
Hey, @jpolitz ! A remote learner in my Python Stepik MAIT is also working through the Java one, and he's reporting some bugs. I've fixed a few Stepik typos, but he found a typo in the code example on this step:

https://stepik.org/lesson/609849/step/1?unit=605131

Specifically, this line:

```java
boolean[] row1 = {true, true, false false};
```

is missing a comma between indices 2 and 3; it should be the following:

```java
boolean[] row1 = {true, true, false, false};
```

I also wonder if it may make sense to enable comments on the course so that learners can report bugs on the specific steps they occur?

**Comment by jpolitz** [comment]
Thanks! Fixed. It was actually fixed in the code and just needed to update the iframe URL.

Do you monitor the comments on the books you work on? How much work is it to do that?

**Comment by niemasd** [comment]
Yes, I monitor the comments on the books I work on. I usually check once per day, and there's usually not more than 5-10 comments; usually more frequent comments early on in the release, and this mellows out as time goes on (likely due to revisions I make based on earlier comments, students finding their questions already asked + answered in the comments, etc.). For my Data Structures text, I think I now get maybe 1 non-CSE100-student comment per week on average, and they're typically just "Great course!" or like engaging with the materials (but don't necessitate a response)
